### ISSUE TITLE
Prediction line is inverted

### ISSUE THREAD

**Issue by drewrosebush** [ruralinnovation/proj-fcc-report#3]
https://github.com/ruralinnovation/proj-fcc-report/blob/a6a28403bb2076c48c743f77c9bc9d8112c38a8a/ms-eda.qmd#L83

You can swap what you're predicting (`lm_ms <- lm(tot_loc ~ cnt_ms, data = vt)`) OR you can swap out the axis and dots

`plot(vt$tot_loc, vt$cnt_ms,  col = "#DF536B50", asp = 1,  xlab = "cnt of fcc locations", ylab = "cnt of MS buildings") `

**Comment by defuneste** [comment]
@drewrosebush we can close this one (now :P)
